<?php
global $handset_index;
$handset_index = array(
 array("DoCoMo/1.0/N502i","handset_reg_0.inc"),
 array("KDDI-ST2B","handset_reg_1.inc"),
 array("LG/U96","handset_reg_2.inc"),
 array("MOT-JA","handset_reg_3.inc"),
 array("Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; Smartphone; 176x220; SPV C500; OpVer 4.1.1.0)","handset_reg_4.inc"),
 array("Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 NokiaE90-1/07.24","handset_reg_5.inc"),
 array("Nokia6126","handset_reg_6.inc"),
 array("Panasonic-GAD67/","handset_reg_7.inc"),
 array("SAGEM-myT-22","handset_reg_8.inc"),
 array("SAMSUNG-SGH-Z150/1.0 SHP/VPP/R5 SMM-MMS/1.2.0 profile/MIDP-2.0 configuration/CLDC-13","handset_reg_9.inc"),
 array("SGH-Z500","handset_reg_10.inc"),
 array("SonyEricssonK610i","handset_reg_11.inc"),
 array("UP.Browser/3.01","handset_reg_12.inc"),
 array("ZTEA3","handset_reg_13.inc"),
  );
?>
