<?php
/**
 * EIROCA PORTAL SYSTEM APPLICATION - Mobile Application
 *
 * Copyright (C) 2002-2008 by Enrico Croce & Simona Burzio
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License <http://www.opensource.org/gpl-license.html>
 * for more details..
 *
 * The latest version of EIROCA PORTAL SYSTEM can be obtained from:
 * http://www.eiroca.net
 *
 * @author Enrico Croce & Simona Burzio (staff@eiroca.net)
 * @copyright Copyright (C) 2003-2008 Enrico Croce & Simona Burzio
 * @version 0.3
 * @link http://www.eiroca.net
 */

if (!defined('REDIR_PATH'))   { define('REDIR_PATH',   "index.php"); }
$CONFIG["path_log"]         = "./logs/";
$CONFIG["path_counters"]    = "./counters/";

?>
