<?php
global $handset_index;
$handset_index = array(
 array("DoCoMo/2.0 7","handset_reg_0.inc"),
 array("LG-G7050 UP.Browser/6.2.2 (GUI) MMP/1.0","handset_reg_1.inc"),
 array("MOT-A835","handset_reg_2.inc"),
 array("MOT-W375","handset_reg_3.inc"),
 array("N7100 ","handset_reg_4.inc"),
 array("Nokia6600/1.0 (3.44","handset_reg_5.inc"),
 array("portalmmm/2.0 LG342i(c3","handset_reg_6.inc"),
 array("SAMSUNG-SGH-E39","handset_reg_7.inc"),
 array("SEC-SGHE720C","handset_reg_8.inc"),
 array("SIE-S68","handset_reg_9.inc"),
 array("SonyEricssonZ208/","handset_reg_10.inc"),
 array("ZTE-F86","handset_reg_11.inc"),
  );
?>
