<?php
global $handset_index;
$handset_index = array(
 array("DoCoMo/1.0/NM502i","handset_reg_0.inc"),
 array("LG-CU500 ","handset_reg_1.inc"),
 array("Mitsu/2.0 ","handset_reg_2.inc"),
 array("MOT-V333","handset_reg_3.inc"),
 array("Mozilla/4.0 SonyEricssonV","handset_reg_4.inc"),
 array("Nokia5500","handset_reg_5.inc"),
 array("NOKIA_RUNNING_UPBROWSER4","handset_reg_6.inc"),
 array("SAGEM-my400X","handset_reg_7.inc"),
 array("SAMSUNG-SGH-X481/","handset_reg_8.inc"),
 array("SendoS600/03","handset_reg_9.inc"),
 array("SonyEricssonK508i/R2AE","handset_reg_10.inc"),
 array("TSM340/","handset_reg_11.inc"),
 array("ZTE-F86","handset_reg_12.inc"),
  );
?>
