<?php
global $handset_index;
$handset_index = array(
 array("DoCoMo/2.0 P700","handset_reg_0.inc"),
 array("LG-L1100 UP.Browser/6.2","handset_reg_1.inc"),
 array("MOT-C980M","handset_reg_2.inc"),
 array("Mozilla/4.0 (compatible; MSIE 4.01; Windows CE; PPC; MDA Vario/2","handset_reg_3.inc"),
 array("Nokia3100b/","handset_reg_4.inc"),
 array("NokiaN-GageQD/1.0","handset_reg_5.inc"),
 array("Sagem-my3","handset_reg_6.inc"),
 array("SAMSUNG-SGH-Z170/1.0 SHP/VPP/R5 NetFront/3.4 SMM-MMS/1.2.0","handset_reg_7.inc"),
 array("SHARP-TQ-GX-L15","handset_reg_8.inc"),
 array("SonyEricssonP802","handset_reg_9.inc"),
 array("vx800","handset_reg_10.inc"),
 array("ZTE-F86","handset_reg_11.inc"),
  );
?>
