body { background-color: #EEE8F7; color: #000000; }
.COL1 { color: #442367;}
.COL2 { color: #A981D3;}
.HR25 { width: 25%; }
.HR50 { width: 50%; }
.HR75 { width: 75%; }
.RIGHT { text-align: right; }
.CENTER { text-align: center; }
.FADE { width: 100%; border-style: none; text-align: center; color: #FFFFFF; padding: 0%; border-collapse: collapse;
<?php global $MODEL; if ($MODEL=="Nokia3650") { echo "margin: -5px"; } ?>
}
.BKG0 { background-color: #A981D3; }
.BKG0_MED { background-color: #A981D3; width: 30%; }
.BKG0_BIG { background-color: #A981D3; width: 50%; }
.BKG1 { background-color: #B08BD8; }
.BKG2 { background-color: #B998DC; }
.BKG3 { background-color: #C7ABE2; }
.BKG4 { background-color: #D5BFEA; }
.BKG5 { background-color: #DFCFEF; }
.BKG5_MED { background-color: #DFCFEF; width: 30%; }
.BKG5_BIG { background-color: #DFCFEF; width: 50%; }