<?php
global $handset_index;
$handset_index = array(
 array("DoCoMo/1.0/SO503i/c1","handset_reg_0.inc"),
 array("LG-G30","handset_reg_1.inc"),
 array("MOT-A-1F","handset_reg_2.inc"),
 array("MOT-V545","handset_reg_3.inc"),
 array("Mozilla/5.0 (SymbianOS/9.2; U; Series60/3.1 Nokia5700/3.8","handset_reg_4.inc"),
 array("Nokia6220/2.0 (","handset_reg_5.inc"),
 array("PANTECH G2","handset_reg_6.inc"),
 array("SAGEM-myX5-5","handset_reg_7.inc"),
 array("SCH-A600 ","handset_reg_8.inc"),
 array("SIE-A65","handset_reg_9.inc"),
 array("SonyEricssonT302/","handset_reg_10.inc"),
 array("WAPUniverse/2","handset_reg_11.inc"),
 array("ZTE-F86","handset_reg_12.inc"),
  );
?>
